aliases:
  1.png: 什么？_shenme？
  2.png: 你没事吧_nimeishiba
  3.png: 吃惊_chijing
  4.png: 吐舌_tushe
  5.png: 呜呜呜_wuwuwu
  6.png: 哦耶_oye
  7.png: 流汗_liuhan
  8.png: 就是你_jiushini
  9.png: 呵呵_hehe
  10.png: 哼!_heng!
  11.png: 睡觉_shuijiao
  12.png: 撑头_chengtou
  13.png: 噗噗_pupu
  14.png: 送你礼物_songniliwu
  15.png: 非常感谢_feichangganxie
  16.png: 给你钱_geiniqian
  17.png: 流泪_liulei
  18.png: 虔诚_qiancheng
  19.png: 西八_xiba
  20.png: 鞠躬_jugong
chinese_name: 崔高兴收藏集
english_name: cui-gao-xing-shou-cang-ji
source: https://www.bilibili.com/h5/mall/digital-card/home?act_id=101689&from=emoji&f_source=garb&-Abrowser=live&hybrid_set_header=2&navhide=1&anchor_task=1
source_description: 表情包版权归原作者所有
tags: {}
