aliases:
  1.png: ok_ok
  2.png: 我选择_woxuanze
  3.png: 报警_baojing
  4.png: 命苦_mingku
  5.png: 单推人民币_dantuirenminbi
  6.png: 人生态度_renshengtaidu
  7.png: 好的_haode
  8.png: 去哪？_quna？
  9.png: 摸鱼_moyu
  10.png: 崩溃_bengkui
  11.png: 鲨鲨_shasha
  12.png: 打工人_dagongren
  13.png: 牛_niu
  14.png: 啊_a
  15.png: 回家_huijia
  16.png: 摸摸_momo
  17.png: 虚假打工人_xujiadagongren
  18.png: 真正打工人_zhenzhengdagongren
  19.png: 收到_shoudao
  20.png: 一拍即合_yipaijihe
chinese_name: 发疯小黄豆
english_name: fa-feng-xiao-huang-dou
source: https://www.bilibili.com/h5/mall/digital-card/home?act_id=100170&from=emoji&f_source=garb&-Abrowser=live&hybrid_set_header=2&navhide=1&anchor_task=1
source_description: 表情包版权归原作者所有
tags: {}
