aliases:
  1.png: 乖巧_guaiqiao
  2.png: 比心_bixin
  3.png: 颤抖_chandou
  4.png: 期待_qidai
  5.png: 喵_miao
  6.png: 生日快乐_shengrikuaile
  7.png: 摔倒_shuaidao
  8.png: 哈哈哈_hahaha
  9.png: 生气_shengqi
  10.png: 困_kun
  11.png: 恼怒_naonu
  12.png: 哭_ku
  13.png: 心虚_xinxu
  14.png: 呵呵_hehe
  15.png: 躺_tang
  16.png: 钱来_qianlai
  17.png: 谁先来_shuixianlai
  18.png: 麻了_male
  19.png: 疑惑_yihuo
  20.png: 惊讶_jingya
chinese_name: 崔高兴日历符卡
english_name: cui-gao-xing-ri-li-fu-ka
source: https://www.bilibili.com/h5/mall/digital-card/home?act_id=101689&from=emoji&f_source=garb&-Abrowser=live&hybrid_set_header=2&navhide=1&anchor_task=1
source_description: 表情包版权归原作者所有
tags: {}
