aliases:
  azuki_san01.png: ''
  azuki_san02.png: ''
  azuki_san03.png: ''
  azuki_san04.png: ''
  azuki_san05.png: ''
  azuki_san06.png: ''
  azuki_san07.png: ''
  azuki_san08.png: ''
  azuki_san09.png: ''
  azuki_san10.png: ''
  azuki_san11.png: ''
  azuki_san12.png: ''
  azuki_san13.png: ''
  azuki_san14.png: ''
  azuki_san15.png: ''
  azuki_san16.png: ''
  azuki_san17.png: ''
  azuki_san18.png: ''
  azuki_san19.png: ''
  azuki_san20.gif: ''
  azuki_san21.gif: ''
  azuki_san22.gif: ''
  azuki_san23.gif: ''
  azuki_san24.gif: ''
  azuki_san25.gif: ''
  azuki_san26.gif: ''
chinese_name: azuki_san
english_name: Azuki_San
source: 网络
source_description: null
tags: {}
