aliases:
  aileaile.png: 爱了爱了
  aini.png: 爱泥
  chong.png: 冲
  ding.png: 盯
  hahaha.png: 哈哈哈
  male.png: 麻了
  moyu.png: 摸鱼
  moailaozi.png: 莫挨老子
  nibuduijin.png: 你不对劲
  qiguaidezhishi.png: 奇怪的知识
  qingni.png: 请你
  rangwokankan.png: 让我看看
  sanlesanle.png: 散了散了
  shengrikuaile.png: 生日快乐
  woshixuesheng.png: 我是学生
  xingxingyan.png: 星星眼
  xiuxi.png: 休息
  yijiansanlian.png: 一键三连
  yi.png: 噫
  zhenbuchuo.png: 针不戳
chinese_name: 暹罗猫小豆泥 · 遇见泥
english_name: xian-luo-mao-xiao-dou-ni- · -yu-jian-ni
source: https://www.bilibili.com/h5/mall/equity-link/collect-home?item_id=39087&isdiy=0&part=emoji_package&from=emoji&f_source=garb&vmid=479603158&native.theme=1&navhide=1
source_description: 表情包版权归原作者所有
tags: {}
