aliases:
  1.png: 加油_jiayou
  2.png: 我打_woda
  3.png: 我看看_wokankan
  4.png: 在干嘛_zaiganma
  5.png: 麻了_male
  6.png: 不急_buji
  7.png: 当当_dangdang
  8.png: 冲鸭_chongya
  9.png: 来喽_lailou
  10.png: 服了_fule
  11.png: 拜拜_baibai
  12.png: 暗中观察_anzhongguancha
  13.png: 你没事吧_nimeishiba
  14.png: 咋了_zale
  15.png: 惊_jing
  16.png: 就这_jiuzhe
  17.png: 懵_meng
  18.png: 开心_kaixin
  19.png: 好棒_haobang
  20.png: 什么_shenme
chinese_name: 疯狂动物城2表情包
english_name: feng-kuang-dong-wu-cheng-2-biao-qing-bao
source: https://www.bilibili.com/h5/mall/digital-card/home?act_id=110618&from=emoji&f_source=garb&-Abrowser=live&hybrid_set_header=2&navhide=1&anchor_task=1
source_description: 表情包版权归原作者所有
tags: {}
