aliases:
  1.png: 听歌_tingge
  2.png: 吹口哨_chuikoushao
  3.png: 博学_boxue
  4.png: go_go
  5.png: 呀比_yabi
  6.png: 害羞_haixiu
  7.png: 瞥_pie
  8.png: 劈叉_picha
  9.png: 强壮_qiangzhuang
  10.png: 开心_kaixin
  11.png: 哭_ku
  12.png: 爱心_aixin
  13.png: 我吗_woma
  14.png: 惬意_qieyi
  15.png: 戴眼镜_daiyanjing
  16.png: 熬夜_aoye
  17.png: 嘿嘿_heihei
  18.png: 喝茶_hecha
  19.png: 比心_bixin
  20.png: 思考_sikao
chinese_name: 豆姆蛙表情
english_name: dou-mu-wa-biao-qing
source: https://www.bilibili.com/h5/mall/digital-card/home?act_id=107383&from=emoji&f_source=garb&-Abrowser=live&hybrid_set_header=2&navhide=1&anchor_task=1
source_description: 表情包版权归原作者所有
tags: {}
