aliases:
  1.png: 洗澡_xizao
  2.png: 顶呱呱_dingguagua
  3.png: 我也_woye
  4.png: 头大_touda
  5.png: 哭哭_kuku
  6.png: 哇_wa
  7.png: 喜欢_xihuan
  8.png: 干杯_ganbei
  9.png: 思考_sikao
  10.png: 偷看_toukan
  11.png: 就这_jiuzhe
  12.png: 太棒啦_taibangla
  13.png: 好方_haofang
  14.png: 啊_a
  15.png: 送你_songni
chinese_name: 豆姆蛙
english_name: dou-mu-wa
source: https://www.bilibili.com/h5/mall/equity-link/collect-home?item_id=1685599447001&isdiy=0&part=emoji_package&from=emoji&f_source=garb&vmid=479603158&native.theme=1&navhide=1
source_description: 表情包版权归原作者所有
tags: {}
